apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: togglemaster

resources:
  - auth-job.yaml
  - flag-job.yaml
  - targeting-job.yaml

configMapGenerator:
  - name: auth-init-sql
    files:
      - init.sql=../../auth-service/db/init.sql

  - name: flag-init-sql
    files:
      - init.sql=../../flag-service/db/init.sql

  - name: targeting-init-sql
    files:
      - init.sql=../../targeting-service/db/init.sql

generatorOptions:
  disableNameSuffixHash: true