apiVersion: v1
kind: ConfigMap
metadata:
  name: togglemaster-config
data:
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/429464396702/togglemaster-evaluation-events"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  RDS_AUTH_ENDPOINT: "rds-postgres-auth.cptcc8odbie7.us-east-1.rds.amazonaws.com"
  RDS_FLAG_ENDPOINT: "rds-postgres-flag.cptcc8odbie7.us-east-1.rds.amazonaws.com"
  RDS_TARGETING_ENDPOINT: "rds-postgres-targeting.cptcc8odbie7.us-east-1.rds.amazonaws.com"
  REDIS_ENDPOINT: "togglemaster-redis.hgrreh.0001.use1.cache.amazonaws.com"