apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-secrets
  namespace: togglemaster
type: Opaque
data:
  POSTGRES_USER: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cG9zdGdyZXMxMjM="
  MASTER_KEY: "YWRtaW4tc2VjcmV0by0xMjM="
  SERVICE_API_KEY: "dG1fa2V5X2xvY2FsX2Rldl8xMjM="
  AWS_ACCESS_KEY_ID: "QVNJQVdIN1FTVU9QTVlYRDJUQ1o="
  AWS_SECRET_ACCESS_KEY: "anEza1FKQUVqWmtuUWFDWEhFS20zNDJieUtwSngwekthMTlncFRTbA=="
  AWS_SESSION_TOKEN: "SVFvSmIzSnBaMmx1WDJWakVPNy8vLy8vLy8vLy93RWFDWFZ6TFhkbGMzUXRNaUpHTUVRQ0lIMXVCcWFuWk82cXRCVkk4MXZnT1NQbFQxWVU2S1gzSGxvYzZNWk5HQUh6QWlBTkJ3TkNCSWlLRDk5RFlEWUZMQnoxUTVTUkNPL25IVHJSWXZNT1lvelBGQ3EvQWdpMi8vLy8vLy8vLy84QkVBQWFERFF5T1RRMk5ETTVOamN3TWlJTU1wSVY1c3l6Tm1hZThJRWNLcE1Dcng1N0w3NldwSmJCbWJ6WlJ6WEl5VENCMTIxTG9KL05UZUNJS1o0Y0ZXMkF0bDkyRTBUUFk2cFZwT3lkMjdGTi9QVlY3R2ZBck5rbUZtZ1llVVkydlVIY1VJaVlkbGRUSUV1Y3dDQ0JaUTVqcExXZlAwUlpuUFVDY2ROdjBGTFl6RkV4bmpzeURKWGJteFVuSEwyUi9CMk8wZGJMQy9sckw5czRXRkxRWVYwNDluZ1hzVncyN1Y5RkN3clhLTkRObVFzVEVFbjk3MmRJNXNBUGhwZzZyVUNaS3dJZGNTcGJML3BjU1ltV2tCTXVqYjhoODRBd0ZVc0EreXh5d2lJVzQxUW0zMGtPTzRmd2JZNGVkR0ZGRFY1dlg1NWdBS1hTaWc4WFkvblpkVnIxekw0TkhoaHMwdEdabURmaW5SWlc2Qk5OVEtCL3dHYUlwa2JtS0w0QWpsR3ZpMGk4SCtmRFl5MWF5OHM0N2o3ZC8vb3dpT0xEMGdZNm5nR1JiVDkrS3M4VmRmMWZ6aEZYWVNDTDh1UkdtVTV0MDQ0Y09zV3U1bzgxQW9lQ3ZMWEVrV0YxN2Q4WWh3S2JZMEtxWGx4ckhDc1Bzdi9jK3ZTNmVuYTk4MnRkQlV0OURvdUtLT21Ca2srS1dFSzJJMjZGYVFrUDJoN0QrRTdNY2o3OUpNSmhUQnFPZm1rUFhpRGJIM01MdWhSYTRNMG9mWm1nb21JZVlMSy9nemt0NWZFT2t4T2dxaWczODkwYVdMcjNZakw1a0RON0JQQndabHF6U1E9PQ=="
