apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: togglemaster

configMapGenerator:
  - name: auth-init-sql
    files:
      - init.sql=auth/init.sql

  - name: flag-init-sql
    files:
      - init.sql=flag/init.sql

  - name: targeting-init-sql
    files:
      - init.sql=targeting/init.sql

resources:
  - auth-job.yaml
  - flag-job.yaml
  - targeting-job.yaml

generatorOptions:
  disableNameSuffixHash: true