apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  labels:
    app: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics-service
        image: analytics-service
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: AWS_SQS_URL
          valueFrom:
            configMapKeyRef:
              name: togglemaster-config
              key: AWS_SQS_URL
        - name: AWS_DYNAMODB_TABLE
          valueFrom:
            configMapKeyRef:
              name: togglemaster-config
              key: AWS_DYNAMODB_TABLE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: togglemaster-config
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: togglemaster-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: togglemaster-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: togglemaster-secrets
              key: AWS_SESSION_TOKEN