apiVersion: v1
kind: ConfigMap
metadata:
  name: togglemaster-config
data:
  AWS_REGION: "A PREENCHER"
  AWS_SQS_URL: "A PREENCHER"
  AWS_DYNAMODB_TABLE: "A PREENCHER"
  RDS_AUTH_ENDPOINT: "A PREENCHER"
  RDS_FLAG_ENDPOINT: "A PREENCHER"
  RDS_TARGETING_ENDPOINT: "A PREENCHER"
  REDIS_ENDPOINT: "A PREENCHER"
