apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-secrets
type: Opaque
data:
  POSTGRES_USER: "A PREENCHER"
  POSTGRES_PASSWORD: "A PREENCHER"
  MASTER_KEY: "A PREENCHER"
  SERVICE_API_KEY: "A PREENCHER"
  AWS_ACCESS_KEY_ID: "A PREENCHER"
  AWS_SECRET_ACCESS_KEY: "A PREENCHER"
  AWS_SESSION_TOKEN: "A PREENCHER"