apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  labels:
    app: targeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting
  template:
    metadata:
      labels:
        app: targeting
    spec:
      containers:
      - name: targeting-service
        image: targeting-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: togglemaster-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: togglemaster-secrets
              key: POSTGRES_PASSWORD
        - name: RDS_TARGETING_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: togglemaster-config
              key: RDS_TARGETING_ENDPOINT
        - name: DATABASE_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(RDS_TARGETING_ENDPOINT):5432/targeting_db"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8001"
        - name: PORT
          value: "8003"
---
apiVersion: v1
kind: Service
metadata:
  name: targeting-service
spec:
  type: ClusterIP
  selector:
    app: targeting
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003